// <auto-generated />
namespace SigalRApp.Migration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201703020722401_removeColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
